"use client";import {useEffect,useState} from "react";import Link from "next/link";
const messageFor=(code:string,fallback:string)=>({pending_verification_exists:"Doanh nghiệp đã có yêu cầu xác minh đang chờ xử lý.",business_access_denied:"Bạn không có quyền gửi xác minh cho doanh nghiệp này.",invalid_business:"Thông tin doanh nghiệp chưa hợp lệ.",internal_error:"Hệ thống đang bận, vui lòng thử lại sau."} as Record<string,string>)[code]||fallback;
export default function BusinessCenter(){const[items,setItems]=useState<any[]>([]),[checks,setChecks]=useState<any[]>([]),[form,setForm]=useState({slug:"",legal_name:"",display_name:"",description:"",website_url:""}),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/user/me/businesses"),fetch("/api/user/me/business-verifications")]);if(!a.ok||!b.ok){setMsg("Không thể tải Business Center. Vui lòng thử lại.");return}setItems((await a.json()).data||[]);setChecks((await b.json()).data||[])}catch{setMsg("Không thể kết nối Business Center.")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function create(e:React.FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/user/businesses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json().catch(()=>({}));if(r.ok){setMsg("Đã tạo hồ sơ. Hãy gửi yêu cầu xác minh.");setForm({slug:"",legal_name:"",display_name:"",description:"",website_url:""});load()}else setMsg(messageFor(j.error,"Không thể tạo doanh nghiệp."))}
async function verify(id:string){const statement=prompt("Mô tả ngắn căn cứ xác minh doanh nghiệp:");if(statement===null)return;setBusy(id);try{const r=await fetch("/api/user/businesses/"+id+"/verification-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({method:"manual",statement,evidence_ref:""})});const j=await r.json().catch(()=>({}));setMsg(r.ok?"Đã gửi yêu cầu xác minh.":messageFor(j.error,"Không thể gửi xác minh."));await load()}catch{setMsg("Không thể kết nối dịch vụ xác minh.")}finally{setBusy("")}}
return <div className="businessCenter">{loading&&<p className="actionMessage">Đang tải dữ liệu doanh nghiệp…</p>}<section className="publicPanel"><h2>Doanh nghiệp của tôi</h2>{items.length?items.map(x=><div className="businessBranch" key={x.id}><b>{x.display_name}</b><span>{x.verification_status} · quyền {x.role} ({x.ownership_status})</span><div>{x.verification_status==="verified"?<Link href={"/business/"+x.slug}>Xem hồ sơ công khai</Link>:x.verification_status==="pending"?<span>Đang chờ xác minh</span>:x.ownership_status==="pending"||x.ownership_status==="verified"?<button className="readAll" disabled={busy===x.id} onClick={()=>verify(x.id)}>{busy===x.id?"Đang gửi…":"Gửi xác minh"}</button>:<span>Không thể gửi xác minh với trạng thái quyền hiện tại</span>}</div></div>):<div className="emptyPublic">Bạn chưa có hồ sơ doanh nghiệp.</div>}</section>
<section className="publicPanel"><h2>Tạo hồ sơ doanh nghiệp</h2><form className="actionForm" onSubmit={create}><label>Tên hiển thị<input required minLength={2} maxLength={200} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>Tên pháp lý<input required minLength={2} maxLength={200} value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase()})}/></label><label>Website<input value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/></label><label>Mô tả<textarea maxLength={4000} rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button>Tạo doanh nghiệp</button>{msg&&<p className="actionMessage">{msg}</p>}</form></section>
<section className="publicPanel"><h2>Lịch sử xác minh</h2>{checks.length?checks.map(x=><div className="businessBranch" key={x.id}><b>{x.display_name}</b><span>{x.method} · {x.status}</span></div>):<div className="emptyPublic">Chưa có yêu cầu xác minh.</div>}</section></div>}
