"use client";import {useEffect,useState} from "react";import Link from "next/link";
export default function UserDashboard(){const[follows,setFollows]=useState<any[]>([]),[notes,setNotes]=useState<any[]>([]),[unread,setUnread]=useState(0),[loading,setLoading]=useState(true);
async function load(){setLoading(true);const [f,n,s]=await Promise.all([fetch("/api/user/me/follows"),fetch("/api/user/me/notifications"),fetch("/api/user/me/notifications/summary")]);if(f.ok)setFollows((await f.json()).data||[]);if(n.ok)setNotes((await n.json()).data||[]);if(s.ok)setUnread((await s.json()).unread||0);setLoading(false)}
useEffect(()=>{load()},[]);
async function read(id:string){await fetch("/api/user/me/notifications/"+id+"/read",{method:"PATCH"});load()}
async function readAll(){await fetch("/api/user/me/notifications/read-all",{method:"PATCH"});load()}
if(loading)return <div className="dashboardEmpty">Đang tải dữ liệu của bạn...</div>;
return <div className="userGrid"><section className="publicPanel"><div className="panelHead"><div><h2>Số đang theo dõi</h2><p>Các số bạn muốn nhận cập nhật.</p></div><strong>{follows.length}</strong></div>{follows.length?follows.map((x:any)=><Link className="followRow" key={x.id} href={"/phone/"+encodeURIComponent(x.e164)}><div><b>{x.e164}</b><span>{x.reputation_label||"unknown"} · {x.report_count||0} báo cáo</span></div><span>→</span></Link>):<div className="emptyPublic">Bạn chưa theo dõi số nào.</div>}</section><section className="publicPanel"><div className="panelHead"><div><h2>Thông báo</h2><p>Cập nhật mới từ các số bạn theo dõi.</p></div><strong>{unread} mới</strong></div>{unread>0&&<button className="readAll" onClick={readAll}>Đánh dấu tất cả đã đọc</button>}{notes.length?notes.map((x:any)=><button className={"notificationRow "+(x.read_at?"isRead":"")} key={x.id} onClick={()=>!x.read_at&&read(x.id)}><div><b>{label(x.event_type)}</b><span>{formatDate(x.created_at)}</span></div>{!x.read_at&&<i/>}</button>):<div className="emptyPublic">Chưa có thông báo.</div>}</section></div>}
function label(v:string){const m:any={identity_updated:"Danh tính đã được cập nhật",reputation_changed:"Uy tín số điện thoại thay đổi",new_report:"Có báo cáo mới",verification_changed:"Trạng thái xác minh thay đổi",footprint_updated:"Dấu vết Internet được cập nhật"};return m[v]||"Có cập nhật mới"}
function formatDate(v:any){if(!v)return"";try{return new Intl.DateTimeFormat("vi-VN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return String(v)}}
