package httpserver
import("context";"crypto/subtle";"database/sql";"net/http";"strconv";"time")
type AdminHandler struct{DB *sql.DB;Token string}
func(a AdminHandler)authorized(r *http.Request)bool{if a.Token==""{return false};expected:="Bearer "+a.Token;actual:=r.Header.Get("Authorization");return len(actual)==len(expected)&&subtle.ConstantTimeCompare([]byte(actual),[]byte(expected))==1}
func(a AdminHandler)Dashboard(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();var phones,verified,reports,claims,comments,users,footprint int64;err:=a.DB.QueryRowContext(ctx,`SELECT (SELECT COUNT(*) FROM phone_numbers),(SELECT COUNT(*) FROM phone_numbers WHERE verification_status='verified'),(SELECT COUNT(*) FROM phone_reports WHERE status='pending'),(SELECT COUNT(*) FROM phone_claims WHERE status='pending'),(SELECT COUNT(*) FROM phone_comments WHERE status='pending'),(SELECT COUNT(*) FROM user_accounts),(SELECT COUNT(*) FROM phone_web_occurrences WHERE is_active=TRUE)`).Scan(&phones,&verified,&reports,&claims,&comments,&users,&footprint);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]any{"phones":phones,"verified":verified,"pending_reports":reports,"pending_claims":claims,"pending_comments":comments,"users":users,"active_footprint":footprint})}
func(a AdminHandler)Reports(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT id::text,e164,reason::text,comment,status::text,created_at FROM phone_reports ORDER BY created_at DESC LIMIT $1`,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,e164,reason,status string;var comment *string;var created time.Time;if rows.Scan(&id,&e164,&reason,&comment,&status,&created)==nil{items=append(items,map[string]any{"id":id,"e164":e164,"reason":reason,"comment":comment,"status":status,"created_at":created})}};writeJSON(w,200,map[string]any{"data":items})}

func(a AdminHandler)Comments(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT c.id::text,p.e164,c.body,c.status,c.helpful_count,c.created_at FROM phone_comments c JOIN phone_numbers p ON p.id=c.phone_number_id ORDER BY CASE WHEN c.status='pending' THEN 0 ELSE 1 END,c.created_at DESC LIMIT $1`,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,e164,body,status string;var helpful int64;var created time.Time;if rows.Scan(&id,&e164,&body,&status,&helpful,&created)==nil{items=append(items,map[string]any{"id":id,"e164":e164,"body":body,"status":status,"helpful_count":helpful,"created_at":created})}};writeJSON(w,200,map[string]any{"data":items})}

func(a AdminHandler) Phones(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};q:=r.URL.Query().Get("q");limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT id::text,e164,verification_status::text,seo_status::text,report_count,search_count,updated_at FROM phone_numbers WHERE $1='' OR e164 ILIKE '%'||$1||'%' ORDER BY updated_at DESC LIMIT $2`,q,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,e164,verification,seo string;var reports,searches int64;var updated time.Time;if rows.Scan(&id,&e164,&verification,&seo,&reports,&searches,&updated)==nil{items=append(items,map[string]any{"id":id,"e164":e164,"verification_status":verification,"seo_status":seo,"report_count":reports,"search_count":searches,"updated_at":updated})}};writeJSON(w,200,map[string]any{"data":items})}
func(a AdminHandler) Operations(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();var scans,seo,notifications int64;err:=a.DB.QueryRowContext(ctx,`SELECT (SELECT COUNT(*) FROM phone_web_scan_jobs WHERE status IN ('pending','running')),(SELECT COUNT(*) FROM phone_numbers WHERE seo_status IN ('discovered','review')),(SELECT COUNT(*) FROM user_notifications WHERE read_at IS NULL)`).Scan(&scans,&seo,&notifications);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]any{"footprint_jobs":scans,"seo_review":seo,"unread_notifications":notifications})}

func(a AdminHandler) Users(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT id::text,subject,created_at FROM user_accounts ORDER BY created_at DESC LIMIT $1`,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,subject string;var created time.Time;if rows.Scan(&id,&subject,&created)==nil{items=append(items,map[string]any{"id":id,"subject":subject,"created_at":created})}};writeJSON(w,200,map[string]any{"data":items})}
func(a AdminHandler) Footprint(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT o.id::text,p.e164,o.domain,o.url,o.page_title,o.category::text,o.detected_at FROM phone_web_occurrences o JOIN phone_numbers p ON p.id=o.phone_number_id WHERE o.is_active=TRUE ORDER BY o.detected_at DESC LIMIT $1`,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,e164,domain,url,category string;var title *string;var detected time.Time;if rows.Scan(&id,&e164,&domain,&url,&title,&category,&detected)==nil{items=append(items,map[string]any{"id":id,"e164":e164,"domain":domain,"url":url,"page_title":title,"category":category,"detected_at":detected})}};writeJSON(w,200,map[string]any{"data":items})}

func(a AdminHandler) Identities(w http.ResponseWriter,r *http.Request){if !a.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));if limit<1||limit>100{limit=50};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();rows,err:=a.DB.QueryContext(ctx,`SELECT i.id::text,p.e164,i.kind::text,i.display_name,i.confidence_score,p.verification_status::text,i.is_primary FROM phone_identities i JOIN phone_numbers p ON p.id=i.phone_number_id ORDER BY i.is_primary DESC,i.confidence_score DESC LIMIT $1`,limit);if err!=nil{writeJSON(w,500,map[string]string{"error":"internal_error"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,e164,kind,name,verification string;var confidence float64;var primary bool;if rows.Scan(&id,&e164,&kind,&name,&confidence,&verification,&primary)==nil{items=append(items,map[string]any{"id":id,"e164":e164,"kind":kind,"display_name":name,"confidence_score":confidence,"verification_status":verification,"is_primary":primary})}};writeJSON(w,200,map[string]any{"data":items})}
