package httpserver

import ("context";"crypto/subtle";"encoding/json";"errors";"net/http";"time";"github.com/wuangmmo/sodienthoai-platform/apps/api/internal/phone")
type ModerationHandler struct{Service phone.Service;Token string;Auth *AdminAuthenticator}
type moderationInput struct{Status string `json:"status"`}
func (h ModerationHandler) authorized(r *http.Request)bool{if h.Auth!=nil{if _,ok:=h.Auth.authenticate(r);ok{return true}};if h.Token==""{return false};expected:="Bearer "+h.Token;actual:=r.Header.Get("Authorization");return len(actual)==len(expected)&&subtle.ConstantTimeCompare([]byte(actual),[]byte(expected))==1}
func (h ModerationHandler) Report(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in moderationInput;if json.NewDecoder(http.MaxBytesReader(w,r.Body,4096)).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();if err:=h.Service.ModerateReport(ctx,r.PathValue("id"),in.Status);err!=nil{if errors.Is(err,phone.ErrInvalidModeration){writeJSON(w,400,map[string]string{"error":"invalid_status"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}
func (h ModerationHandler) Claim(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in moderationInput;if json.NewDecoder(r.Body).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();if err:=h.Service.ModerateClaim(ctx,r.PathValue("id"),in.Status);err!=nil{if errors.Is(err,phone.ErrInvalidModeration){writeJSON(w,400,map[string]string{"error":"invalid_status"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}

func (h ModerationHandler) Comment(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in moderationInput;if json.NewDecoder(http.MaxBytesReader(w,r.Body,4096)).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();if err:=h.Service.ModerateComment(ctx,r.PathValue("id"),in.Status);err!=nil{if errors.Is(err,phone.ErrInvalidCommentModeration){writeJSON(w,400,map[string]string{"error":"invalid_status"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}


type businessModerationInput struct{Status string `json:"status"`;Note string `json:"note"`}
func(h ModerationHandler) Appeal(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in businessModerationInput;if json.NewDecoder(http.MaxBytesReader(w,r.Body,8192)).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();if err:=h.Service.ModerateAppeal(ctx,r.PathValue("id"),in.Status,"admin",in.Note);err!=nil{if errors.Is(err,phone.ErrInvalidBusinessModeration){writeJSON(w,409,map[string]string{"error":"invalid_transition"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}
func(h ModerationHandler) BusinessVerification(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in businessModerationInput;if json.NewDecoder(http.MaxBytesReader(w,r.Body,8192)).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),5*time.Second);defer cancel();if err:=h.Service.ModerateBusinessVerification(ctx,r.PathValue("id"),in.Status,"admin",in.Note);err!=nil{if errors.Is(err,phone.ErrInvalidBusinessModeration){writeJSON(w,409,map[string]string{"error":"invalid_transition"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}
func(h ModerationHandler) BusinessReview(w http.ResponseWriter,r *http.Request){if !h.authorized(r){writeJSON(w,401,map[string]string{"error":"unauthorized"});return};var in businessModerationInput;if json.NewDecoder(http.MaxBytesReader(w,r.Body,8192)).Decode(&in)!=nil{writeJSON(w,400,map[string]string{"error":"invalid_request"});return};ctx,cancel:=context.WithTimeout(r.Context(),3*time.Second);defer cancel();if err:=h.Service.ModerateBusinessReview(ctx,r.PathValue("id"),in.Status,"admin");err!=nil{if errors.Is(err,phone.ErrInvalidBusinessModeration){writeJSON(w,409,map[string]string{"error":"invalid_transition"});return};writeJSON(w,500,map[string]string{"error":"internal_error"});return};writeJSON(w,200,map[string]string{"status":"updated"})}
